version: '2'

volumes:
  mechadocker-database:
    external: true

services:
  database:
    container_name: mechadocker_database
    image: mongo
    volumes:
      - mechadocker-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}
    restart: "no"

  crashfile-detector:
    volumes:
      - ./crashfile-detector/app:/app/:ro
    ports:
      - 8000:8000
    environment:
      - WEB_CONCURRENCY=2
    build: ./crashfile-detector
    restart: unless-stopped

  logviewer:
    build: ./logviewer
    volumes:
      - ./logviewer/:/app/
    command: python app.py
    ports:
      - 8880:8880
    depends_on:
      - database
    restart: unless-stopped

  mechabowser:
    build: ./MechaBowser
    volumes:
      - ./MechaBowser/:/MechaBowser/
      - ./.git/modules/MechaBowser/:/.git/modules/MechaBowser/
    environment:
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: python bot.py
    depends_on:
      - database
      - crashfile-detector
    restart: unless-stopped

  parakarry:
    build: ./Parakarry
    volumes:
      - ./Parakarry/:/Parakarry/
      - ./.git/modules/Parakarry/:/.git/modules/Parakarry/
    command: python bot.py
    depends_on:
      - database
    restart: unless-stopped
