version: '2'

volumes:
  mechadocker-database:
    external: true

services:
  database:
    container_name: mechadocker_database
    image: mongo
    volumes:
      - mechadocker-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}
    restart: "no"

  logviewer:
    build: ./logviewer
    volumes:
      - ./logviewer/:/app/
    command: python app.py
    ports:
      - 8880:8880
    depends_on:
      - database
    restart: unless-stopped

  mechabowser:
    build: ./MechaBowser
    volumes:
      - ./MechaBowser/:/MechaBowser/
      - ./.git/modules/MechaBowser/:/.git/modules/MechaBowser/
    command: python bot.py
    depends_on:
      - database
    restart: unless-stopped

  parakarry:
    build: ./Parakarry
    volumes:
      - ./Parakarry/:/Parakarry/
      - ./.git/modules/Parakarry/:/.git/modules/Parakarry/
    command: python bot.py
    depends_on:
      - database
    restart: unless-stopped
