version: '2'

volumes:
  mechabowser-database:
    external: true

services:
  database:
    container_name: mechadocker_database
    image: mongo
    volumes:
      - mechabowser-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}

  logviewer:
    build: 
      context: .
      dockerfile: logviewer.dockerfile
    volumes:
      - ./logviewer/:/app/
    command: python app.py
    ports:
      - 8880:8880
    environment:
      - HOST=0.0.0.0
    depends_on:
      - database