version: '2'

volumes:
  mechadocker-database:
    external: true

services:
  database:
    container_name: mechadocker_database
    image: mongo
    volumes:
      - mechadocker-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}
    restart: "no"

  mechabowser-cov:
    build:
      context: ./MechaBowser
      dockerfile: coverage.dockerfile
    volumes:
      - ./MechaBowser/:/MechaBowser/
      - ./.git/modules/MechaBowser/:/.git/modules/MechaBowser/
    environment:
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: bash coverage.sh
    depends_on:
      - database
    restart: unless-stopped
